### ISSUE TITLE
--filename option not working (file not found)

### ISSUE THREAD

**Issue by atikrahman1** [punk-security/dnsReaper#110]
Seems like the --filename function is broken somehow no matter what is says the file not found 

```docker run punksecurity/dnsreaper --filename sub.txt file --out stdout```

![image](https://user-images.githubusercontent.com/25384315/186601187-e900010e-16ea-403e-9e8f-25371bbb625c.png)

**Comment by imnotbrandon** [comment]
Hi there,
Docker containers run in an isolated environment, so the reason why the file was not found is because it doesn't exist in the container.

To use a file from the host system, you'll need to map your directory e.g.
`docker run -v /home/atikqur/sub.txt:/tmp/sub.txt punksecurity/dnsreaper  --filename /tmp/sub.txt file --out stdout`

**Comment by danieloateslee** [comment]
Closing the issue as the answre was in the https://hub.docker.com/r/punksecurity/dnsreaper Readme.
