### ISSUE TITLE
User support: How to run on Kali Linux

### ISSUE THREAD

**Issue by Steiner-254** [punk-security/dnsReaper#116]
~ Running the tool has got some errors:

┌──(root💀kali)-[/home/steiner254/dnsReaper]
└─# docker run punksecurity/dnsreaper single --domain target.com
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: short-name "punksecurity/dnsreaper" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
                                                                                                                             
┌──(root💀kali)-[/home/steiner254/dnsReaper]
└─#

**Comment by SimonGurney** [comment]
Hi!

The error means your docker installation doesn't work because its not finding our dockerhub, which is the default docker container registry.

I haven't ran containers on Kali, but we'll take a look today and get you some instructions

**Comment by jw-barker** [comment]
Hi, 
This is an issue with podman and because shortnames arent resolved by default. 

You can either run the command:
`docker run docker.io/punksecurity/dnsreaper single --domain target.com`

Alternatively you can add the following to the registries.conf file which will then resolve shortnames by default.
`unqualified-search-registries = ["docker.io"]`

**Comment by Steiner-254** [comment]
Alright, thanks :)
