### ISSUE TITLE
AWS Route 53 no longer vulnerable

### ISSUE THREAD

**Issue by thr3athunt3r** [punk-security/dnsReaper#122]
AWS Route 53 no longer vulnerable to takeover domains with dangling delegation records

**Comment by SimonGurney** [comment]
My theory is that sometime sit doesnt work because the domain si actually configured, but as a private hosted zone ands not public.  This means it is installed on the nameservers but only resolves when queired from the same aws account.

Unfortunately, you cannot tell if its not configured at all or configured as a private zone.

**Comment by thr3athunt3r** [comment]
My case is domain with ns records but not in a hosted zone is not vulnerable. Failed with 7 domains tested which have signature 'aws_ns' at yesterday.

Some references from googling:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/protection-from-dangling-dns.html
https://github.com/indianajson/can-i-take-over-dns/issues/1


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SimonGurney** [comment]
Hmmm, its a fair point.  It's a bit of an edge case.  

This takeover is definitely possible in some cases, but there are some protections (which you have linked).

I'll add a comment to the information we return for this signature to state that its a bit of an edge case.
